# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_LGG.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1008, 686)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(0, 0, 11, 11)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 220, 131, 81))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 131, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setMargin(11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.skullStripping = QtGui.QPushButton(self.layoutWidget)
        self.skullStripping.setObjectName(_fromUtf8("skullStripping"))
        self.verticalLayout_8.addWidget(self.skullStripping)
        self.biasFieldCorrection = QtGui.QPushButton(self.layoutWidget)
        self.biasFieldCorrection.setObjectName(_fromUtf8("biasFieldCorrection"))
        self.verticalLayout_8.addWidget(self.biasFieldCorrection)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 310, 131, 131))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.registration = QtGui.QPushButton(self.groupBox_7)
        self.registration.setGeometry(QtCore.QRect(60, 112, 51, 18))
        self.registration.setObjectName(_fromUtf8("registration"))
        self.rigidCB = QtGui.QCheckBox(self.groupBox_7)
        self.rigidCB.setGeometry(QtCore.QRect(2, 22, 61, 18))
        self.rigidCB.setObjectName(_fromUtf8("rigidCB"))
        self.affineCB = QtGui.QCheckBox(self.groupBox_7)
        self.affineCB.setGeometry(QtCore.QRect(70, 22, 61, 18))
        self.affineCB.setObjectName(_fromUtf8("affineCB"))
        self.nonrigidCB = QtGui.QCheckBox(self.groupBox_7)
        self.nonrigidCB.setGeometry(QtCore.QRect(1, 46, 101, 18))
        self.nonrigidCB.setObjectName(_fromUtf8("nonrigidCB"))
        self.atlasCB = QtGui.QCheckBox(self.groupBox_7)
        self.atlasCB.setGeometry(QtCore.QRect(1, 68, 121, 18))
        self.atlasCB.setObjectName(_fromUtf8("atlasCB"))
        self.atlasCBS = QtGui.QCheckBox(self.groupBox_7)
        self.atlasCBS.setGeometry(QtCore.QRect(1, 90, 121, 18))
        self.atlasCBS.setObjectName(_fromUtf8("atlasCBS"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 440, 131, 181))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.preProcSeg = QtGui.QPushButton(self.groupBox_8)
        self.preProcSeg.setGeometry(QtCore.QRect(30, 43, 80, 18))
        self.preProcSeg.setObjectName(_fromUtf8("preProcSeg"))
        self.segmentation2 = QtGui.QPushButton(self.groupBox_8)
        self.segmentation2.setGeometry(QtCore.QRect(30, 21, 80, 18))
        self.segmentation2.setObjectName(_fromUtf8("segmentation2"))
        self.segmentation3 = QtGui.QPushButton(self.groupBox_8)
        self.segmentation3.setGeometry(QtCore.QRect(30, 65, 80, 18))
        self.segmentation3.setObjectName(_fromUtf8("segmentation3"))
        self.load3DSeg = QtGui.QPushButton(self.groupBox_8)
        self.load3DSeg.setGeometry(QtCore.QRect(30, 111, 80, 18))
        self.load3DSeg.setObjectName(_fromUtf8("load3DSeg"))
        self.overlaySeg = QtGui.QCheckBox(self.groupBox_8)
        self.overlaySeg.setGeometry(QtCore.QRect(2, 88, 53, 18))
        self.overlaySeg.setObjectName(_fromUtf8("overlaySeg"))
        self.alphaSet = QtGui.QSlider(self.groupBox_8)
        self.alphaSet.setGeometry(QtCore.QRect(59, 91, 61, 16))
        self.alphaSet.setOrientation(QtCore.Qt.Horizontal)
        self.alphaSet.setObjectName(_fromUtf8("alphaSet"))
        self.loadPatientData = QtGui.QPushButton(self.groupBox)
        self.loadPatientData.setGeometry(QtCore.QRect(60, 190, 61, 18))
        self.loadPatientData.setObjectName(_fromUtf8("loadPatientData"))
        self.searchPatientData = QtGui.QPushButton(self.groupBox)
        self.searchPatientData.setGeometry(QtCore.QRect(40, 50, 80, 18))
        self.searchPatientData.setObjectName(_fromUtf8("searchPatientData"))
        self.browseT1C = QtGui.QPushButton(self.groupBox)
        self.browseT1C.setGeometry(QtCore.QRect(10, 160, 51, 18))
        self.browseT1C.setObjectName(_fromUtf8("browseT1C"))
        self.browseT2 = QtGui.QPushButton(self.groupBox)
        self.browseT2.setGeometry(QtCore.QRect(68, 160, 51, 20))
        self.browseT2.setObjectName(_fromUtf8("browseT2"))
        self.T2Image = QtGui.QComboBox(self.groupBox)
        self.T2Image.setGeometry(QtCore.QRect(30, 130, 91, 22))
        self.T2Image.setObjectName(_fromUtf8("T2Image"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(2, 130, 17, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.useT2 = QtGui.QCheckBox(self.groupBox)
        self.useT2.setGeometry(QtCore.QRect(18, 130, 21, 21))
        self.useT2.setText(_fromUtf8(""))
        self.useT2.setObjectName(_fromUtf8("useT2"))
        self.T1Contrast = QtGui.QComboBox(self.groupBox)
        self.T1Contrast.setGeometry(QtCore.QRect(30, 105, 91, 22))
        self.T1Contrast.setObjectName(_fromUtf8("T1Contrast"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(2, 105, 21, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.useT1 = QtGui.QCheckBox(self.groupBox)
        self.useT1.setGeometry(QtCore.QRect(17, 105, 21, 21))
        self.useT1.setText(_fromUtf8(""))
        self.useT1.setObjectName(_fromUtf8("useT1"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(2, 80, 28, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.imageSeries = QtGui.QComboBox(self.groupBox)
        self.imageSeries.setGeometry(QtCore.QRect(34, 80, 91, 22))
        self.imageSeries.setObjectName(_fromUtf8("imageSeries"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(2, 20, 22, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.patientID = QtGui.QComboBox(self.groupBox)
        self.patientID.setGeometry(QtCore.QRect(28, 20, 91, 23))
        self.patientID.setEditable(True)
        self.patientID.setObjectName(_fromUtf8("patientID"))
        self.tacticCB = QtGui.QCheckBox(self.groupBox)
        self.tacticCB.setGeometry(QtCore.QRect(10, 190, 51, 21))
        self.tacticCB.setObjectName(_fromUtf8("tacticCB"))
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.figure1 = figure1Widget(self.centralWidget)
        self.figure1.setObjectName(_fromUtf8("figure1"))
        self.horizontalLayout_4.addWidget(self.figure1)
        self.figure2 = figure2Widget(self.centralWidget)
        self.figure2.setObjectName(_fromUtf8("figure2"))
        self.horizontalLayout_4.addWidget(self.figure2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setMargin(11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.figure3 = figure3Widget(self.centralWidget)
        self.figure3.setObjectName(_fromUtf8("figure3"))
        self.horizontalLayout_9.addWidget(self.figure3)
        self.figure4 = figure4Widget(self.centralWidget)
        self.figure4.setObjectName(_fromUtf8("figure4"))
        self.horizontalLayout_9.addWidget(self.figure4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.imageSlider = QtGui.QSlider(self.centralWidget)
        self.imageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imageSlider.setObjectName(_fromUtf8("imageSlider"))
        self.verticalLayout_3.addWidget(self.imageSlider)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setMargin(11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.freehand = QtGui.QCheckBox(self.groupBox_3)
        self.freehand.setObjectName(_fromUtf8("freehand"))
        self.verticalLayout_7.addWidget(self.freehand)
        self.polygon = QtGui.QCheckBox(self.groupBox_3)
        self.polygon.setObjectName(_fromUtf8("polygon"))
        self.verticalLayout_7.addWidget(self.polygon)
        self.rectangle = QtGui.QCheckBox(self.groupBox_3)
        self.rectangle.setObjectName(_fromUtf8("rectangle"))
        self.verticalLayout_7.addWidget(self.rectangle)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 59, 16))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 6, 91, 381))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.saveGroup = QtGui.QGroupBox(self.groupBox_5)
        self.saveGroup.setGeometry(QtCore.QRect(0, 220, 91, 71))
        self.saveGroup.setObjectName(_fromUtf8("saveGroup"))
        self.saveROI = QtGui.QPushButton(self.saveGroup)
        self.saveROI.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.saveROI.setObjectName(_fromUtf8("saveROI"))
        self.saveContour = QtGui.QPushButton(self.saveGroup)
        self.saveContour.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.saveContour.setObjectName(_fromUtf8("saveContour"))
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 80, 91, 141))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.brushSize = QtGui.QDoubleSpinBox(self.groupBox_9)
        self.brushSize.setGeometry(QtCore.QRect(30, 22, 50, 19))
        self.brushSize.setObjectName(_fromUtf8("brushSize"))
        self.label_9 = QtGui.QLabel(self.groupBox_9)
        self.label_9.setGeometry(QtCore.QRect(2, 22, 41, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.volBrushCB = QtGui.QCheckBox(self.groupBox_9)
        self.volBrushCB.setGeometry(QtCore.QRect(1, 46, 91, 18))
        self.volBrushCB.setObjectName(_fromUtf8("volBrushCB"))
        self.brushUpdateButton = QtGui.QPushButton(self.groupBox_9)
        self.brushUpdateButton.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.brushUpdateButton.setObjectName(_fromUtf8("brushUpdateButton"))
        self.isoBrushCB = QtGui.QCheckBox(self.groupBox_9)
        self.isoBrushCB.setGeometry(QtCore.QRect(1, 68, 91, 18))
        self.isoBrushCB.setObjectName(_fromUtf8("isoBrushCB"))
        self.resetSegButton = QtGui.QPushButton(self.groupBox_9)
        self.resetSegButton.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.resetSegButton.setObjectName(_fromUtf8("resetSegButton"))
        self.loadGroup = QtGui.QGroupBox(self.groupBox_5)
        self.loadGroup.setGeometry(QtCore.QRect(0, 290, 91, 71))
        self.loadGroup.setObjectName(_fromUtf8("loadGroup"))
        self.loadROI = QtGui.QPushButton(self.loadGroup)
        self.loadROI.setGeometry(QtCore.QRect(10, 21, 61, 16))
        self.loadROI.setObjectName(_fromUtf8("loadROI"))
        self.pushButton_7 = QtGui.QPushButton(self.loadGroup)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_2.setGeometry(QtCore.QRect(2, 40, 71, 16))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_3.setGeometry(QtCore.QRect(2, 60, 71, 16))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton = QtGui.QPushButton(self.groupBox_5)
        self.pushButton.setGeometry(QtCore.QRect(2, 21, 71, 16))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.testButton = QtGui.QPushButton(self.groupBox_6)
        self.testButton.setGeometry(QtCore.QRect(10, 420, 61, 16))
        self.testButton.setObjectName(_fromUtf8("testButton"))
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(2, 390, 31, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit.setGeometry(QtCore.QRect(30, 400, 41, 16))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1008, 20))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Patient Data                 ", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Pre-processing", None))
        self.skullStripping.setText(_translate("MainWindow", "SkullStripping", None))
        self.biasFieldCorrection.setText(_translate("MainWindow", "BiasFieldCorrection", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Registration", None))
        self.registration.setText(_translate("MainWindow", "Run", None))
        self.rigidCB.setText(_translate("MainWindow", "rigid", None))
        self.affineCB.setText(_translate("MainWindow", "affine", None))
        self.nonrigidCB.setText(_translate("MainWindow", "nonrigid", None))
        self.atlasCB.setText(_translate("MainWindow", "atlas (unstripped)", None))
        self.atlasCBS.setText(_translate("MainWindow", "atlas (stripped)", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Segmentation", None))
        self.preProcSeg.setText(_translate("MainWindow", "3D-preProc", None))
        self.segmentation2.setText(_translate("MainWindow", "2D Seg", None))
        self.segmentation3.setText(_translate("MainWindow", "3D Seg", None))
        self.load3DSeg.setText(_translate("MainWindow", "load 3D Seg", None))
        self.overlaySeg.setText(_translate("MainWindow", "Overlay", None))
        self.loadPatientData.setText(_translate("MainWindow", "load", None))
        self.searchPatientData.setText(_translate("MainWindow", "search", None))
        self.browseT1C.setText(_translate("MainWindow", "T1", None))
        self.browseT2.setText(_translate("MainWindow", "T2", None))
        self.label_3.setText(_translate("MainWindow", "T2 :", None))
        self.label_2.setText(_translate("MainWindow", "T1 :", None))
        self.label_5.setText(_translate("MainWindow", "Exam:", None))
        self.label.setText(_translate("MainWindow", "ID   :", None))
        self.tacticCB.setText(_translate("MainWindow", "DB", None))
        self.label_4.setText(_translate("MainWindow", "Brain Tumor Segmentation v4.0", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Drawing Tools       ", None))
        self.freehand.setText(_translate("MainWindow", "Freehand", None))
        self.polygon.setText(_translate("MainWindow", "Polygon", None))
        self.rectangle.setText(_translate("MainWindow", "Rectangle", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "ROI Edit", None))
        self.saveGroup.setTitle(_translate("MainWindow", "save", None))
        self.saveROI.setText(_translate("MainWindow", "ROI", None))
        self.saveContour.setText(_translate("MainWindow", "Contours", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Brush", None))
        self.label_9.setText(_translate("MainWindow", "Size:", None))
        self.volBrushCB.setText(_translate("MainWindow", "Erase", None))
        self.brushUpdateButton.setText(_translate("MainWindow", "update", None))
        self.isoBrushCB.setText(_translate("MainWindow", "Correct", None))
        self.resetSegButton.setText(_translate("MainWindow", "reset", None))
        self.loadGroup.setTitle(_translate("MainWindow", "load", None))
        self.loadROI.setText(_translate("MainWindow", "ROI", None))
        self.pushButton_7.setText(_translate("MainWindow", "Contours", None))
        self.pushButton_2.setText(_translate("MainWindow", "edit", None))
        self.pushButton_3.setText(_translate("MainWindow", "delete", None))
        self.pushButton.setText(_translate("MainWindow", "display", None))
        self.testButton.setText(_translate("MainWindow", "batchRun", None))
        self.label_6.setText(_translate("MainWindow", "slice", None))

from figure1widgetFile import figure1Widget
from figure2widgetFile import figure2Widget
from figure3widgetFile import figure3Widget
from figure4widgetFile import figure4Widget
